### ISSUE TITLE
Documentations?

### ISSUE THREAD

**Issue by RamonGiovane** [afonasev/flake8-breakpoint#89]
* Operating System: Linux Mint 20.2
* Python version: 3.10
* flake8-breakpoint version used: 1.1

### Description

May you provide any instructions on how to use it?

Is it a flake8 plugin? Can I integrate with it?
If it's standalone, which command should I call?
Can I use it on pre-commit?

**Comment by afonasev** [comment]
Yes, it is flake8 plugin. You can use it only with flake8.
```
pip install flake8 flake8-breakpoint
flake8 .
```
[This is instruction for pre-commit](https://flake8.pycqa.org/en/latest/user/using-hooks.html)
